language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

install:
  - cd ./public/main
  - npm install
  - cd ../dashboard
  - npm install
  - cd ../..
  - npm install

jobs:
  include:
    - stage: test
      script:
      - npm test
      - echo "lol wut"
